### PR TITLE
Add .nmvrc set on 8.9

### PR DESCRIPTION
**Pull request by chevdor**
I ran into a few issues with other versions of node.
The compatible min version can be documented but it will make dev´s lives easier when this is specified in such a file.

### CODE REVIEW

**Comment by LefterisJP** [comment]
My node version in archlinux is v8.2.1. Does it not work for you? I am not familiar with nvm. How does it work? Also can you set your commit email and author name in your git settings properly to the same email setup in your github? So that the commits are matched to your account.

**Comment by chevdor** [comment]
Honestly I thew 'a' number to get started. I will test with 8.2.1 and let you know.

nvm is 'virtualenv' for nodeJS. Perfect for the lazy. You can set it up so it automatically look for those .nvmrc files and switch your env automatically when 'cd'ing in a folder. 

Using `nvm use` will also look for this file and switch to the version defined in there. I like projects with such `.nvmrc` file as it does not disturb people not using nvm and still help them to know the recommended version while making it a breeze for the nvm users.

I will change my config to match the GH account.

**Comment by LefterisJP** [comment]
Cool seems that with 8.2 it also works for you. Can you squash them into one commit and then I can merge.

**Comment by chevdor** [comment]
I noticed no problem using `8.2.1`. I did not specify `8.2.1` but `8.2`. It will resolve to whatever version 8.2.x is the freshest. That´s `8.2.1` currently.

**Comment by LefterisJP** [comment]
Cool. Can you also squash the 2 commits into one?

**Pull request merged**
