### PR TITLE
Fix 156

### PR DESCRIPTION
**Pull request by kascheri12**
With these changes, I can now scroll to the bottom of the section and read all available information as seen in various screenshots:

screen shot 2018-09-21 at 11 59 20 pm

screen shot 2018-09-21 at 11 59 43 pm

screen shot 2018-09-22 at 12 08 45 am

### CODE REVIEW

**Comment by kelsos** [comment]
Do you really need all this code to fix the height overflow issue?

**Comment by kelsos** [comment]
@kascheri12 can you check how this works for you? https://github.com/kelsos/rotkehlchen/commit/c73e12f6d095a0a8f39e8080ef8328899beb0b42

**Comment by kascheri12** [comment]
@kelsos No, probably don't need all my code. It's a shotty attempt at fixing the problem for myself only. I look forward to trying your solution later this afternoon.

**Comment by kelsos** [comment]
@kascheri12 No worries, you had the right idea on where to look :+1:

**Comment by kascheri12** [comment]
Thanks for the solution @kelsos!
The min-height attribute was causing the issue.
@LefterisJP this is ready.

**Comment by LefterisJP** [comment]
@kascheri12 looks good. Can you add a changelog entry for solving 156?

**Comment by kascheri12** [comment]
Hopefully next time I remember that changelog.. 😆

**Pull request merged**
