### PR TITLE
[WIP] Covert JS to Typescript

### PR DESCRIPTION
**Pull request by eayoungs**
First steps in using Typescript

### CODE REVIEW

**Comment by eayoungs** [comment]
Looks like the failure has to do with calling tests, which I assume don't yet exist since there is a Gitcoin bounty for that as well. Should we remove this requirement to get the tests passing again? @LefterisJP 
Thx!

**Comment by LefterisJP** [comment]
Hey, no that can't happen. The tests that are there are all working and should pass.

**Comment by eayoungs** [comment]
Sorry for the delay here. line 2202 of the CI test says "No test files found".

**Comment by LefterisJP** [comment]
Closing this in favour of: https://github.com/rotkehlchenio/rotkehlchen/pull/111

**Pull request closed without merging**
