### PR TITLE
Updates .nvmrc to v10.2.0

### PR DESCRIPTION
**Pull request by kelsos**
I added some config to my .zshrc to automatically change the node version automatically because my default version is now 12.x which is incompatible with electron 3 and I have to change it every time by hand.

The current version of node.js specified in `.nvmrc` is too old.

According to [electron-releases](https://electronjs.org/releases/stable?page=11#3.0.0) the 3.x version of electron uses v10.2.0 of node.js.

### CODE REVIEW

**Comment by LefterisJP** [comment]
Hey looks fine. But the UI tests should also be ran to make sure nothing breaks.

But for some reason some other tests seem to be broken at the moment. I have to look them up. Seems like cryptocompare historical data slightly changed?

**Comment by LefterisJP** [comment]
an issue for the tests: https://github.com/rotkehlchenio/rotkehlchen/issues/377

**Comment by kelsos** [comment]
Do you use nvmrc for anything on the ci? Otherwise I am not sure if it makes sense to run the ui tests.

**Comment by LefterisJP** [comment]
@kelsos doesn't nvmrc lock the node version? Wouldn't that affect all ui stuff?

**Comment by kelsos** [comment]
@LefterisJP .nvmrc is mostly for the development environment so for the file to be used you have to have nvm installed on your machine and loaded in your .bashrc/.zshrc

All the changes I did to Rotkehlchen so far where with nvm using v10.13.0 of node.js either way. In the CI i couldn't find any link to nvm so I am guessing you where using the system's/image's installed node.js package.

**Comment by LefterisJP** [comment]
Merging as the unknown binance asset is unrelated and means we gotta add support for one more asset.

**Pull request merged**
