### PR TITLE
Implement logout functionality and expose it in the UI

### LINKED ISSUE #178: Log out button does not work -- needs backend implementation too
## Problem Definition

When pressing the logout button the user is not logged out of everything. Instead a blank screen is given and the login prompt is not presented.

2018-10-04-002253_198x194_scrot

And in the chrome console we get the following error:

2018-10-04-002214_647x116_scrot

## System Description

Rotkehlchen commit: 97bcd4993911c8458f7694e7341e005c70c2813d
System: Archlinux

## Tasks

- [ ] Create a logout function in the backend [server](https://github.com/rotkehlchenio/rotkehlchen/blob/8ebed0ab3bc1bc61e38c1a88a1abfce0b47e2eb4/rotkehlchen/server.py) that touches the appropriate parts of the backend and logs out the user from everywhere. Make sure this is invoked when "log out" is pressed.

- [ ] If logout is succesful then properly show the rotkehlchen login prompt again.

### PR DESCRIPTION
**Pull request by LefterisJP**
Fix #178

### CODE REVIEW

**Comment by LefterisJP** [comment]
Hey @kelsos can you have a look at the front-end typescript changes?

**Comment by kascheri12** [comment]
Hi @LefterisJP, I'm so glad to see you working on this so quickly. I was trying to find a solution myself but it was nowhere near as sufficient and complete as yours. Thank you for allowing this sort of collaboration! I am so pleased and thankful to be able to look over your shoulder and learn from your implementation.

I have tried this solution you have so far and it seems incomplete to me.

After I confirm sign out, the dashboard does not hide my info.
screen shot 2018-10-06 at 9 32 15 am


Also, after logging back in, I am greeted with this error:
screen shot 2018-10-06 at 9 30 52 am

**Comment by LefterisJP** [comment]
@kascheri12 wow that's funny. For me it does hide the information properly. Let me look at it.

**Comment by LefterisJP** [comment]
@kascheri12 Can you now check if logging out works for you and does not leave anything from the previous session?

**Pull request merged**
