### PR TITLE
Properly encode TradeType

### LINKED ISSUE #309: TradeType is not JSON serializable
## Problem Definition

As the title says. I faced this error when i rebased on latest master.
```
26/02/2019 20:40:54 CET -- ERROR:rotkehlchen.server:Greenlet for task 5 dies with exception: Object of type TradeType is not JSON serializable.
Exception Name: <class 'TypeError'>
Exception Info: Object of type TradeType is not JSON serializable
Traceback:
   File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/server.py", line 115, in _query_async
    result = getattr(self, command)(**kwargs)
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/server.py", line 230, in process_trade_history
    result, error_or_empty = self.rotkehlchen.process_history(start_ts, end_ts)
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/rotkehlchen.py", line 482, in process_history
    end_at_least_ts=end_ts,
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/history.py", line 925, in get_history
    return self.create_history(start_ts, end_ts, end_at_least_ts)
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/history.py", line 764, in create_history
    write_tupledata_history_in_file(history, historyfile_path, start_ts, end_ts)
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/history.py", line 128, in write_tupledata_history_in_file
    write_history_data_in_file(out_history, filepath, start_ts, end_ts)
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/history.py", line 123, in write_history_data_in_file
    outfile.write(rlk_jsondumps(history_dict))
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/utils.py", line 316, in rlk_jsondumps
    return json.dumps(data, cls=RKLEncoder)
  File "/home/rakan/.pyenv/versions/3.7.0/lib/python3.7/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/home/rakan/.pyenv/versions/3.7.0/lib/python3.7/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/rakan/.pyenv/versions/3.7.0/lib/python3.7/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/rakan/Code/Python/rotkehlchen/rotkehlchen/utils.py", line 296, in default
    return json.JSONEncoder.default(self, obj)
  File "/home/rakan/.pyenv/versions/3.7.0/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
```

### PR DESCRIPTION
**Pull request by rakanalh**
Fixes #309

### CODE REVIEW

**Comment by LefterisJP** [comment]
@rakanalh Ah thank you very much. Missed those things as I locally am now working with no cache. This serialization/deserialization to/from json only goes to a json file for caching.

Should probably write tests for these. Does this fix your issue?

**Comment by rakanalh** [comment]
Sorry for not getting back to this yesterday. Yes, it seems to have solved the problem and i was planning on adding more tests as requested, but i was checking out the other issue i told you about.

**Comment by LefterisJP** [comment]
If you can add those tests it would be awesome :heart:

**Comment by rakanalh** [comment]
I'll have it on my todo list for the weekend :+1:

**Pull request merged**
